apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2  # This creates two replicas of your container
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: my-python-container
        image: my-python-container:latest  # This should match your image name
        ports:
        - containerPort: 80
